pypi-xpra: Autospec creation for update from version 4.4.4 to version 4.4.5
Colin Cross (1):
      Pass max buffer size to BrotliEncoderCompress

totaam (86):
      2022.2.2, stuck on 2022.1 for EL8
      only negative values are errors
      bump version
      also silence python3-cryptography on MacOS
      useless statement could actually cause errors
      _NET_WM_NAME is in utf8
      #3793 workaround even more exotic version strings
      #3789 one of these two packages should work?
      fixup package name
      AyatanaAppIndicator3 is AppIndicator3
      backing var had gone missing
      don't run tests on OracleLinux 8
      #3807 merge changes from git master: use uint64_t everywhere
      we don't want a python2 shebang
      match file renaming
      we need pkgconfig
      skip xsettings dpi when the x11 bindings are missing
      fix zero dimension check
      #3802 pandoc is in the EPEL repos
      more useful validation message
      ignore xpra.egg-info
      this syntax avoids warnings
      avoid errors if 'md5' has already been removed
      make it possible to skip 'sha1'
      if we don't have keycodes to map, don't translate them
      add missing import
      #3820 avoid errors with malformed display names
      #3822 always call trap pop after calling trap push
      #3820 doh
      there is no exception to show
      having opengl properties is not sufficient
      tolerate mixed case better
      fix error showing list of valid client encodings
      #3826 honour png/P
      nonsensical: partial revert of c5c8a105fb6c2b535bfed0169208d72433df43c5
      also honour png/L when scrolling
      #3825 also honour 'png/P' when scrolling
      the window mixin requires this one
      don't flood the screen or log file
      doh: negate switch
      continue even if we can't create the cursor we want to use
      ignore 'mod2' aka 'Num_Lock' with Wayland clients
      handle runtime failures gracefully
      always use lossless encoding for 'text', even when scrolling
      don't warn about socket o750 permission for shared sockets
      missing attribute can raise a TypeError here
      unused default implementation should use a valid signature
      clients should not use the session dir for sockets
      fix force_flush_queue: Queue objects have get but not read
      try to lookup ipv6 interfaces
      more resilient: run even without sys.stderr
      remove unused logging argument
      missing comma would cause packages to not be excluded as they should be
      handle 'RGBA' window icon data
      only run systemd-run if supported
      avoid permissions issues with mv
      avoid errors when running without a client
      this is no longer needed - I think
      architecture in filename should be generic so it works on arm64
      avoid compilation errors with gcc version 7 and older
      in v4.4.x, only None values are ignored
      bump version
      update the release notes
      dummy 0.4.1
      must return True to run the handler again
      fail early with a more useful message
      more packaging workarounds
      also clean cpp files
      typo
      stop as soon as we find a valid backend
      only allow logging tweaks via env vars for non-root users
      getuid is posix only
      update the release notes
      fix service update with newer versions of python-zeroconf
      we need more elements to play bell.wav
      ensure the capture instance is ready to produce images
      also send pings on websocket connections
      initialize variable
      docs say we should not process events with negative codes
      Fix side buttons on Win32
      #3822 minimal fix for GLib malloc crash
      fix Atom name memleak
      update the release notes
      only use synthetic unfocus events when needed
      add focus fix to the release notes
      #3822 copy window depth and visual from parent window